import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/toaster';
import RecoilWrapper from '@/components/recoil/wrapper';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'CIT Machine Learning Tools',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <link rel='icon' href='/favicon.ico' type='image/png' />
      <body className={inter.className}>
        <RecoilWrapper>{children}</RecoilWrapper>
        <Toaster />
      </body>
    </html>
  );
}
